# @package _global_

hydra:
  sweep:
    dir: ${env:LOG_DIR}
    subdir: ''
  launcher:
    cpus_per_task: 10
    gpus_per_node: 8
    tasks_per_node: 8
    nodes: 2
    comment: null
    mem_gb: 0
    timeout_min: 4320
    max_num_timeout: 30
    constraint: null
    name: ${hydra.job.config_name}
    submitit_folder: ${hydra.sweep.dir}/submitit/%j
    partition: wav2vec

distributed_training:
  distributed_world_size: 16
  distributed_port: 29671
