# @package _global_

hydra:
  sweep:
    dir: ${env:LOG_DIR}
    subdir: ''
  launcher:
    cpus_per_task: 10
    gpus_per_node: 8
    tasks_per_node: 8
    nodes: 1
    comment: null
    mem_gb: 0
    timeout_min: 4320
    max_num_timeout: 30
    name: w2v_ft
    submitit_folder: ${hydra.sweep.dir}/submitit/%j
    partition: wav2vec
    exclude: a100-st-p4d24xlarge-[897-898,881-882]

distributed_training:
  distributed_world_size: 8
  distributed_port: 29671
