# @package _global_

hydra:
  sweep:
    dir: ${env:LOG_DIR}
    subdir: ''
  launcher:
    cpus_per_task: 10
    gpus_per_node: 8
    tasks_per_node: 8
    nodes: 1
    comment: null
    mem_gb: 250
    timeout_min: 4320
    max_num_timeout: 30
    constraint: volta32gb,ib4
    name: w2v_ft
    submitit_folder: ${hydra.sweep.dir}/submitit/%j
    partition: learnlab,learnfair,devlab

distributed_training:
  distributed_world_size: 8
  distributed_port: 29671
